[
    {
        "keyword": [
            "Developer, Tutor"
        ],
        "isAccepted": false,
        "isBlocked": false,
        "category": "Daily",
        "duration": 30,
        "title": "MERN Stack Tutor",
        "description": "To teach lessons of MERN Stack basics",
        "preferedSkills": "Developer",
        "rateOfPayment": 500,
        "preference": "Any",
        "timeSlot": "5PM-7PM",
        "jobProviderName": "Harish Ponna",
        "contactNumber": 9876543211,
        "city": "Hyderabad",
        "pincode": 500060,
        "address": "road.no 9, Dilsukhnagar, Hyderabad, Telangana, PIN.500060",
        "jobProviderId": "5e8daa039c93560017538a34",
        "jobProviderEmail": "harishponna55@gmail.com",
        "createdAt": "2020-04-07T10:23:16.202Z",
        "updatedAt": "2020-04-07T10:23:16.202Z",
        "__v": 0
    },
    {
        "keyword": [
            "Developer, Tutor"
        ],
        "isAccepted": false,
        "isBlocked": false,
        "category": "Daily",
        "duration": 30,
        "title": "RDBMS Tutor",
        "description": "To teach any relaional databases to my daughter for a month",
        "preferedSkills": "Developer",
        "rateOfPayment": 500,
        "preference": "Any",
        "timeSlot": "5PM-7PM",
        "jobProviderName": "Harish Ponna",
        "contactNumber": 9876543211,
        "city": "Hyderabad",
        "pincode": 500060,
        "address": "road.no 9, Dilsukhnagar, Hyderabad, Telangana, PIN.500060",
        "jobProviderId": "5e8daa039c93560017538a34",
        "jobProviderEmail": "harishponna55@gmail.com",
        "createdAt": "2020-04-06T10:23:12.054Z",
        "updatedAt": "2020-04-06T10:23:12.054Z",
        "__v": 0
    },
    {
        "keyword": [
            "Developer"
        ],
        "isAccepted": false,
        "isBlocked": false,
        "category": "Hourly",
        "duration": 5,
        "title": "Web-site developer",
        "description": "To make a small single page front-end application for my Marketing Bussiness",
        "preferedSkills": "Developer",
        "rateOfPayment": 500,
        "preference": "Any",
        "timeSlot": "12PM-5PM",
        "jobProviderName": "Harish Ponna",
        "contactNumber": 9876543211,
        "city": "Hyderabad",
        "pincode": 500060,
        "address": "road.no 9, Dilsukhnagar, Hyderabad, Telangana, PIN.500060",
        "jobProviderId": "5e8daa039c93560017538a34",
        "jobProviderEmail": "harishponna55@gmail.com",
        "createdAt": "2020-04-05T10:23:18.234Z",
        "updatedAt": "2020-04-05T10:23:18.234Z",
        "__v": 0
    },
    {
        "keyword": [
            "Active, Honest, Educated upto HSC qualified, Literate, English"
        ],
        "isAccepted": false,
        "isBlocked": false,
        "category": "Weekely",
        "duration": 4,
        "title": "Shop Assistant",
        "description": "I need an assistant to assist me in my shop for card making.",
        "preferedSkills": "Active, Honest, Educated upto HSC qualified, Literate, hard worker",
        "rateOfPayment": 5000,
        "preference": "Any",
        "timeSlot": "8AM-7PM",
        "contactNumber": 6512244936,
        "city": "Noida",
        "pincode": 201301,
        "address": "sector 22, Choura rasta, Noida, G.B Nagar, UP, PIN.201301",
        "jobProviderId": "5e8da4219c93560017538a32",
        "jobProviderEmail": "jhasiddhida@gmail.com",
        "jobProviderName": "Jha Siddhida",
        "createdAt": "2020-04-04T10:23:19.288Z",
        "updatedAt": "2020-04-04T10:23:19.288Z",
        "__v": 0
    },
    {
        "keyword": [
            "Cook"
        ],
        "isAccepted": false,
        "isBlocked": false,
        "category": "Daily",
        "duration": 7,
        "title": "Cook",
        "description": "Cooking of food for my family members for a week in afternoon and evening shifts and cleaning the cooking utensils",
        "preferedSkills": "Cooking",
        "rateOfPayment": 150,
        "preference": "Female",
        "timeSlot": "12PM-9PM",
        "jobProviderName": "Harish Ponna",
        "contactNumber": 9876543211,
        "city": "Hyderabad",
        "pincode": 500060,
        "address": "road.no 9, Dilsukhnagar, Hyderabad, Telangana, PIN.500060",
        "jobProviderId": "5e8daa039c93560017538a34",
        "jobProviderEmail": "harishponna55@gmail.com",
        "createdAt": "2020-04-03T10:23:14.085Z",
        "updatedAt": "2020-04-03T10:23:14.085Z",
        "__v": 0
    },

    {
        "keyword": [
            "Active, Honest, Educated upto HSC qualified, Literate, English, electrician"
        ],
        "isAccepted": false,
        "isBlocked": false,
        "category": "Weekely",
        "duration": 1,
        "title": "Electrician",
        "description": "I need an electrician to assist me in in home small scale cottage industry to make motors and Transformers.",
        "preferedSkills": "Active, Honest, Educated upto HSC qualified, Literate, electrician",
        "rateOfPayment": 5000,
        "preference": "Any",
        "timeSlot": "8AM-7PM",
        "contactNumber": 6512244936,
        "city": "Noida",
        "pincode": 201301,
        "address": "sector 22, Choura rasta, Noida, G.B Nagar, UP, PIN.201301",
        "jobProviderId": "5e8da4219c93560017538a32",
        "jobProviderEmail": "jhasiddhida@gmail.com",
        "jobProviderName": "Jha Siddhida",
        "createdAt": "2020-04-01T10:23:18.736Z",
        "updatedAt": "2020-04-01T10:23:18.736Z",
        "__v": 0
    },
    {
        "keyword": [
            "Active, Honest, Educated upto HSC qualified, Literate, English, Full stack Developer"
        ],
        "isAccepted": false,
        "isBlocked": false,
        "category": "Weekely",
        "duration": 1,
        "title": "Developer",
        "description": "I need a developer to assist me in my full stack project development.",
        "preferedSkills": "Active, Honest, Educated upto HSC qualified, Literate, Full stack Developer",
        "rateOfPayment": 5000,
        "preference": "Any",
        "timeSlot": "8AM-7PM",
        "contactNumber": 6512244936,
        "city": "Noida",
        "pincode": 201301,
        "address": "sector 22, Choura rasta, Noida, G.B Nagar, UP, PIN.201301",
        "jobProviderId": "5e8da4219c93560017538a32",
        "jobProviderEmail": "jhasiddhida@gmail.com",
        "jobProviderName": "Jha Siddhida",
        "createdAt": "2020-04-01T10:23:13.515Z",
        "updatedAt": "2020-04-01T10:23:13.515Z",
        "__v": 0
    },
    {
        "keyword": [
            "Plumbing, Sevicing"
        ],
        "isAccepted": false,
        "isBlocked": false,
        "category": "Hourly",
        "duration": 8,
        "title": "Plumbing",
        "description": "Repairing of pipes and home service etc ",
        "preferedSkills": "Plumber",
        "rateOfPayment": 150,
        "preference": "Male",
        "timeSlot": "6PM-10PM",
        "jobProviderName": "Harish Ponna",
        "contactNumber": 9876543211,
        "city": "Hyderabad",
        "pincode": 500060,
        "address": "road.no 9, Dilsukhnagar, Hyderabad, Telangana, PIN.500060",
        "jobProviderId": "5e8daa039c93560017538a34",
        "jobProviderEmail": "harishponna55@gmail.com",
        "createdAt": "2020-04-01T10:23:14.892Z",
        "updatedAt": "2020-04-01T10:23:14.892Z",
        "__v": 0
    },
    {
        "keyword": [
            "Service, Catering"
        ],
        "isAccepted": false,
        "isBlocked": false,
        "category": "Hourly",
        "duration": 4,
        "title": "Catering",
        "description": "Catering of food items and servicing to the people in marriage function hall ",
        "preferedSkills": "Servicing",
        "rateOfPayment": 200,
        "preference": "Any",
        "timeSlot": "6PM-10PM",
        "jobProviderName": "Harish Ponna",
        "contactNumber": 9876543211,
        "city": "Hyderabad",
        "pincode": 500060,
        "address": "road.no 9, Dilsukhnagar, Hyderabad, Telangana, PIN.500060",
        "jobProviderId": "5e8daa039c93560017538a34",
        "jobProviderEmail": "harishponna55@gmail.com",
        "createdAt": "2020-03-08T10:23:16.147Z",
        "updatedAt": "2020-03-08T10:23:16.147Z",
        "__v": 0
    },
    {
        "keyword": [
            "Active, Honest, Educated upto HSC qualified, Literate, English"
        ],
        "isAccepted": false,
        "isBlocked": false,
        "category": "Weekely",
        "duration": 1,
        "title": "Reader",
        "description": "I need a reader to read out loudly Epics.",
        "preferedSkills": "Active, Honest, Educated upto HSC qualified, Literate",
        "rateOfPayment": 4500,
        "preference": "Any",
        "timeSlot": "8AM-7PM",
        "contactNumber": 6512244936,
        "city": "Noida",
        "pincode": 201301,
        "address": "sector 22, Choura rasta, Noida, G.B Nagar, UP, PIN.201301",
        "jobProviderId": "5e8da4219c93560017538a32",
        "jobProviderEmail": "jhasiddhida@gmail.com",
        "jobProviderName": "Jha Siddhida",
        "createdAt": "2020-03-25T10:23:18.680Z",
        "updatedAt": "2020-03-25T10:23:18.680Z",
        "__v": 0
    },

    {
        "keyword": [
            "Helper, Driving, Responsible, Alert"
        ],
        "isAccepted": false,
        "isBlocked": false,
        "category": "Weekely",
        "duration": 1,
        "title": "Driver",
        "description": "I need a Driver to drive me to workplace.",
        "preferedSkills": "Active, Honest, Educated upto HSC qualified, Driving Skilled",
        "rateOfPayment": 4500,
        "preference": "Any",
        "timeSlot": "8AM-7PM",
        "contactNumber": 6512244936,
        "city": "Noida",
        "pincode": 201301,
        "address": "sector 22, Choura rasta, Noida, G.B Nagar, UP, PIN.201301",
        "jobProviderId": "5e8da4219c93560017538a32",
        "jobProviderEmail": "jhasiddhida@gmail.com",
        "jobProviderName": "Jha Siddhida",
        "createdAt": "2020-02-02T10:23:13.705Z",
        "updatedAt": "2020-02-02T10:23:13.705Z",
        "__v": 0
    },
    {
        "keyword": [
            "Helper, Driving, Responsible, Alert"
        ],
        "isAccepted": false,
        "isBlocked": false,
        "category": "Weekely",
        "duration": 1,
        "title": "Driver",
        "description": "I need a Driver to drive me to workplace.",
        "preferedSkills": "Active, Honest, Educated upto HSC qualified, Driving Skilled",
        "rateOfPayment": 4500,
        "preference": "Any",
        "timeSlot": "8AM-7PM",
        "contactNumber": 6512244936,
        "city": "Noida",
        "pincode": 201301,
        "address": "sector 22, Choura rasta, Noida, G.B Nagar, UP, PIN.201301",
        "jobProviderId": "5e8da4219c93560017538a32",
        "jobProviderEmail": "jhasiddhida@gmail.com",
        "jobProviderName": "Jha Siddhida",
        "createdAt": "2020-01-05T10:23:12.560Z",
        "updatedAt": "2020-01-05T10:23:12.560Z",
        "__v": 0
    },
    {
        "keyword": [
            "Helper, Spoken English, Responsible, Alert, Outspoken "
        ],
        "isAccepted": false,
        "isBlocked": false,
        "category": "Monthly",
        "duration": 2,
        "title": "helper",
        "description": "I need a Helper to help me in household chores in my home.",
        "preferedSkills": "Active, Honest, Educated upto HSC qualified, English Skilled",
        "rateOfPayment": 9000,
        "preference": "Any",
        "timeSlot": "8AM-7PM",
        "contactNumber": 6512244936,
        "city": "Noida",
        "pincode": 201301,
        "address": "sector 22, Choura rasta, Noida, G.B Nagar, UP, PIN.201301",
        "jobProviderId": "5e8da4219c93560017538a32",
        "jobProviderEmail": "jhasiddhida@gmail.com",
        "jobProviderName": "Jha Siddhida",
        "createdAt": "2020-02-18T10:23:14.478Z",
        "updatedAt": "2020-02-18T10:23:14.478Z",
        "__v": 0
    },
    {
        "keyword": [
            "English, Spoken English, Responsible, Alert, Outspoken "
        ],
        "isAccepted": false,
        "isBlocked": false,
        "category": "Monthly",
        "duration": 2,
        "title": "Assistant",
        "description": "I need a Assistant to assist me in my shop.",
        "preferedSkills": "Active, Honest, Educated upto HSC qualified, English Skilled",
        "rateOfPayment": 12000,
        "preference": "Any",
        "timeSlot": "8AM-10PM",
        "contactNumber": 6512244936,
        "city": "Noida",
        "pincode": 201301,
        "address": "sector 22, Choura rasta, Noida, G.B Nagar, UP, PIN.201301",
        "jobProviderId": "5e8da4219c93560017538a32",
        "jobProviderEmail": "jhasiddhida@gmail.com",
        "jobProviderName": "Jha Siddhida",
        "createdAt": "2020-02-22T10:23:15.563Z",
        "updatedAt": "2020-02-22T10:23:15.563Z",
        "__v": 0
    },
    {
        "keyword": [
            "English, Spoken English, Responsible "
        ],
        "isAccepted": false,
        "isBlocked": false,
        "category": "Monthly",
        "duration": 2,
        "title": "Typist",
        "description": "I need a Typist for my in home coaching center.",
        "preferedSkills": "Active, Honest, Educated upto HSC qualified, English Skilled",
        "rateOfPayment": 18000,
        "preference": "Any",
        "timeSlot": "1PM-11PM",
        "contactNumber": 6512244936,
        "city": "Noida",
        "pincode": 201301,
        "address": "sector 22, Choura rasta, Noida, G.B Nagar, UP, PIN.201301",
        "jobProviderId": "5e8da4219c93560017538a32",
        "jobProviderEmail": "jhasiddhida@gmail.com",
        "jobProviderName": "Jha Siddhida",
        "createdAt": "2020-04-11T10:23:19.674Z",
        "updatedAt": "2020-04-11T10:23:19.674Z",
        "__v": 0
    },

    {
        "keyword": [
            "English, Spoken English, Teaching, Responsible "
        ],
        "isAccepted": false,
        "isBlocked": false,
        "category": "Monthly",
        "duration": 2,
        "title": "Writer English",
        "description": "I need a English Writer to assistme in my Book Writing.",
        "preferedSkills": "Active, Honest, Educated upto HSC qualified, English Skilled",
        "rateOfPayment": 5000,
        "preference": "Any",
        "timeSlot": "9AM-6PM",
        "contactNumber": 6512244936,
        "city": "Noida",
        "pincode": 201301,
        "address": "sector 22, Choura rasta, Noida, G.B Nagar, UP, PIN.201301",
        "jobProviderId": "5e8da4219c93560017538a32",
        "jobProviderEmail": "jhasiddhida@gmail.com",
        "jobProviderName": "Jha Siddhida",
        "createdAt": "2020-04-21T10:23:11.915Z",
        "updatedAt": "2020-04-21T10:23:11.915Z",
        "__v": 0
    },
    {
        "keyword": [
            "English, Spoken English, Teaching, Responsible "
        ],
        "isAccepted": false,
        "isBlocked": false,
        "category": "Monthly",
        "duration": 2,
        "title": "Tutor English",
        "description": "I need a spoken English Tutor for myself.",
        "preferedSkills": "Active, Honest, Educated upto HSC qualified, English Skilled",
        "rateOfPayment": 5000,
        "preference": "Any",
        "timeSlot": "3PM-6PM",
        "contactNumber": 6512244936,
        "city": "Noida",
        "pincode": 201301,
        "address": "sector 22, Choura rasta, Noida, G.B Nagar, UP, PIN.201301",
        "jobProviderId": "5e8da4219c93560017538a32",
        "jobProviderEmail": "jhasiddhida@gmail.com",
        "jobProviderName": "Jha Siddhida",
        "createdAt": "2020-04-02T10:23:17.484Z",
        "updatedAt": "2020-04-02T10:23:17.484Z",
        "__v": 0
    },
    {
        "keyword": [
            "Maths, Tutor, Teaching, Responsible "
        ],
        "isAccepted": false,
        "isBlocked": false,
        "category": "Monthly",
        "duration": 2,
        "title": "Tutor Maths",
        "description": "I need a maths Tutor to teach in my Coaching intitute for 2 months to the studdents of class 9th and 10th.",
        "preferedSkills": "Active, Honest, Educated upto HSC qualified, Maths Skilled",
        "rateOfPayment": 5000,
        "preference": "Any",
        "timeSlot": "3PM-6PM",
        "contactNumber": 6512244936,
        "city": "Noida",
        "pincode": 201301,
        "address": "sector 22, Choura rasta, Noida, G.B Nagar, UP, PIN.201301",
        "jobProviderId": "5e8da4219c93560017538a32",
        "jobProviderEmail": "jhasiddhida@gmail.com",
        "jobProviderName": "Jha Siddhida",
        "createdAt": "2020-04-15T10:23:11.994Z",
        "updatedAt": "2020-04-15T10:23:11.994Z",
        "__v": 0
    },
    {
        "keyword": [
            "Baby Sitting, Nursing, Teaching, Responsible "
        ],
        "isAccepted": false,
        "isBlocked": false,
        "category": "Daily",
        "duration": 60,
        "title": "Baby Sitter",
        "description": "I need a babysitter to look after my kid",
        "preferedSkills": "Active, Honest, Educated upto HSC qualified",
        "rateOfPayment": 500,
        "preference": "Any",
        "timeSlot": "9AM-6PM",
        "contactNumber": 6512244936,
        "city": "Noida",
        "pincode": 201301,
        "address": "sector 22, Choura rasta, Noida, G.B Nagar, UP, PIN.201301",
        "jobProviderId": "5e8da4219c93560017538a32",
        "jobProviderEmail": "jhasiddhida@gmail.com",
        "jobProviderName": "Jha Siddhida",
        "createdAt": "2020-04-12T10:23:19.169Z",
        "updatedAt": "2020-04-12T10:23:19.169Z",
        "__v": 0
    },
    {
        "keyword": [
            "Sweeping, Moping, Dusting"
        ],
        "isAccepted": false,
        "isBlocked": false,
        "category": "Daily",
        "duration": 7,
        "title": "Cleaner",
        "description": "I need a Cleaner to clean my home inside and outside",
        "preferedSkills": "Sweeping, Moping, Dusting, hardworker, honest",
        "rateOfPayment": 700,
        "preference": "Any",
        "timeSlot": "9AM-6PM",
        "contactNumber": 6512244936,
        "city": "Noida",
        "pincode": 201301,
        "address": "sector 22, Choura rasta, Noida, G.B Nagar, UP, PIN.201301",
        "jobProviderId": "5e8da4219c93560017538a32",
        "jobProviderEmail": "jhasiddhida@gmail.com",
        "jobProviderName": "Jha Siddhida",
        "createdAt": "2020-01-08T10:23:16.111Z",
        "updatedAt": "2020-01-08T10:23:16.111Z",
        "__v": 0
    },

    {
        "keyword": [
            "Sweeping, Moping, Dusting"
        ],
        "isAccepted": false,
        "isBlocked": false,
        "category": "Daily",
        "duration": 7,
        "title": "Cleaner",
        "description": "I need a Cleaner to clean my home inside and outside",
        "preferedSkills": "Sweeping, Moping, Dusting, hardworker, honest",
        "rateOfPayment": 700,
        "preference": "Any",
        "timeSlot": "9AM-6PM",
        "contactNumber": 6512244936,
        "city": "Noida",
        "pincode": 201301,
        "address": "sector 22, Choura rasta, Noida, G.B Nagar, UP, PIN.201301",
        "jobProviderId": "5e8da4219c93560017538a32",
        "jobProviderEmail": "jhasiddhida@gmail.com",
        "jobProviderName": "Jha Siddhida",
        "createdAt": "2020-04-01T10:23:12.134Z",
        "updatedAt": "2020-04-01T10:23:12.134Z",
        "__v": 0
    },
    {
        "keyword": [
            "Developer, Frontend, JavaScript, Web Page Designer"
        ],
        "isAccepted": false,
        "isBlocked": false,
        "category": "Daily",
        "duration": 7,
        "title": "Web Page Designer",
        "description": "I need a Web Page Designer to look after production of my website",
        "preferedSkills": "Java script, HTML, CSS, Bootstrap",
        "rateOfPayment": 700,
        "preference": "Any",
        "timeSlot": "9AM-6PM",
        "jobProviderName": "Jha Siddhida",
        "contactNumber": 6512244936,
        "city": "Noida",
        "pincode": 201301,
        "address": "sector 22, Choura rasta, Noida, G.B Nagar, UP, PIN.201301",
        "jobProviderId": "5e8da4219c93560017538a32",
        "jobProviderEmail": "jhasiddhida@gmail.com",
        "createdAt": "2020-04-02T10:23:19.647Z",
        "updatedAt": "2020-04-02T10:23:19.647Z",
        "__v": 0
    },
    {
        "keyword": [
            "Developer, Frontend, JavaScript"
        ],
        "isAccepted": false,
        "isBlocked": false,
        "category": "Daily",
        "duration": 30,
        "title": "A JavaScript Developer",
        "description": "I need a JavaScript Front end developer to revise my rusted knowledge",
        "preferedSkills": "Java script, HTML, CSS, Bootstrap",
        "rateOfPayment": 700,
        "preference": "Any",
        "timeSlot": "9AM-6PM",
        "jobProviderName": "Jha Siddhida",
        "contactNumber": 6512244936,
        "city": "Noida",
        "pincode": 201301,
        "address": "sector 22, Choura rasta, Noida, G.B Nagar, UP, PIN.201301",
        "jobProviderId": "5e8da4219c93560017538a32",
        "jobProviderEmail": "jhasiddhida@gmail.com",
        "createdAt": "2020-04-01T10:23:18.088Z",
        "updatedAt": "2020-04-01T10:23:18.088Z",
        "__v": 0
    },
    {
        "keyword": [
            "Delivery"
        ],
        "isAccepted": false,
        "isBlocked": false,
        "category": "Hourly",
        "duration": 10,
        "title": "Delivery Boy",
        "description": "Delivery of Products to different location allocated by customers",
        "preferedSkills": "Servicing",
        "rateOfPayment": 100,
        "preference": "Female",
        "timeSlot": "9AM-4PM",
        "jobProviderName": "Harish Ponna",
        "contactNumber": 9876543211,
        "city": "Hyderabad",
        "pincode": 500060,
        "address": "road.no 9, Dilsukhnagar, Hyderabad, Telangana, PIN.500060",
        "jobProviderId": "5e8daa039c93560017538a34",
        "jobProviderEmail": "harishponna55@gmail.com",
        "createdAt": "2020-04-02T10:23:14.414Z",
        "updatedAt": "2020-04-02T10:23:14.414Z",
        "__v": 0
    },
    {
        "keyword": [
            "Service"
        ],
        "isAccepted": false,
        "isBlocked": false,
        "category": "Hourly",
        "duration": 4,
        "title": "Room Service",
        "description": "Cleaning my house and placing the furniture in neat manner and cleaning cooking utensils",
        "preferedSkills": "Servicing",
        "rateOfPayment": 100,
        "preference": "Female",
        "timeSlot": "2pm-6pm",
        "jobProviderName": "Harish Ponna",
        "contactNumber": 9876543211,
        "city": "Hyderabad",
        "pincode": 500060,
        "address": "road.no 9, Dilsukhnagar, Hyderabad, Telangana, PIN.500060",
        "jobProviderId": "5e8daa039c93560017538a34",
        "jobProviderEmail": "harishponna55@gmail.com",
        "createdAt": "2020-04-01T10:23:12.099Z",
        "updatedAt": "2020-04-01T10:23:12.099Z",
        "__v": 0
    },

    {
        "keyword": [
            "Painter, Whitewasher"
        ],
        "isAccepted": false,
        "isBlocked": false,
        "category": "Daily",
        "duration": 30,
        "title": "Painter",
        "description": "I need a Painter to white-wash exterior of my house and design interior of my house",
        "preferedSkills": "Painter",
        "rateOfPayment": 700,
        "preference": "Any",
        "timeSlot": "1pm-6pm",
        "jobProviderName": "Jha Siddhida",
        "contactNumber": 6512244936,
        "city": "Noida",
        "pincode": 201301,
        "address": "sector 22, Choura rasta, Noida, G.B Nagar, UP, PIN.201301",
        "jobProviderId": "5e8da4219c93560017538a32",
        "jobProviderEmail": "jhasiddhida@gmail.com",
        "createdAt": "2020-04-04T10:23:12.342Z",
        "updatedAt": "2020-04-04T10:23:12.342Z",
        "__v": 0
    },
    {
        "keyword": [
            "Pianist"
        ],
        "isAccepted": false,
        "isBlocked": false,
        "category": "Hourly",
        "duration": 5,
        "title": "Piano Tutor",
        "description": "Piano teaching for my kid,who is 10 years old.",
        "preferedSkills": "Pianist",
        "rateOfPayment": 200,
        "preference": "Any",
        "timeSlot": "1pm-6pm",
        "jobProviderName": "Jha Siddhida",
        "contactNumber": 6512244936,
        "city": "Noida",
        "pincode": 201301,
        "address": "sector 22, Choura rasta, Noida, G.B Nagar, UP, PIN.201301",
        "jobProviderId": "5e8da4219c93560017538a32",
        "jobProviderEmail": "jhasiddhida@gmail.com",
        "createdAt": "2020-03-30T10:23:17.413Z",
        "updatedAt": "2020-03-30T10:23:17.413Z",
        "__v": 0
    }

]