
#######################################  SEEKER ROUTES   ###################################3

###################  GET 

###  Account Activation
GET http://localhost:8080/api/accountactivation/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MC4xNzU3NDg2Nzg4NjQ0NjkzMiwiaWF0IjoxNTg1NjkwMjEyfQ.OlKKEDbHysec4Nz7SpN3zF-vfkiB_9jV099gCbNblOI?user=Job-Seeker

### showing all jobs which are available
GET http://localhost:8080/api/jobseeker/searchjobs/allavailablejobs/1/

### filtering jobs by category of hourly, daily, weekly, monthly

GET http://localhost:8080/api/jobseeker/searchjobs/filter/1?category=hourly



### showing single job by jobId
GET http://localhost:8080/api/jobseeker/searchjobs/byjobId/1/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg1NTc1MTI3LCJleHAiOjE1OTE1NzUxMjd9.cPBpN-8uFH1AF4axWOgy0y3VXuiVJRMMhCV9lSijDM4

###  showing jobs accepted by seeker till date
GET http://localhost:8080/api/jobseeker/jobsacceptedtilldate/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg1NTc1MTI3LCJleHAiOjE1OTE1NzUxMjd9.cPBpN-8uFH1AF4axWOgy0y3VXuiVJRMMhCV9lSijDM4

###################  POST

###   Register Seeker Account
POST http://localhost:8080/api/user/register
content-type: application/json

{
  	"name": "Siddhida",
    "email":"jhasiddhidda@gmail.com",
    "password":"123456",
   "aadhaarNumber" :124411789789,
  "gender":"female",
   "contactNumber" : 1234167391,
   "address" : "Ranchi abcdefghtikjjh",
   "role" : "Job-Seeker"
}


###   Login into Seeker Account
POST http://localhost:8080/api/user/login
content-type: application/json

{
    "email":"jhasiddhida@gmail.com",
    "password":"123456",
    "role":"Job-Seeker"
}

### forgot passsword sending system generated password
POST http://localhost:8080/api/user/forgotpassword
Content-Type: application/json

{
  "email":"jhasiddhida@gmail.com",
  "role":"Job-Seeker",
  "aadhaarNumber":123456789789
}

###   Uploading Profile Picture
PATCH http://localhost:8080/api/jobseeker/uploadprofilepicture
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg1NTc1MTI3LCJleHAiOjE1OTE1NzUxMjd9.cPBpN-8uFH1AF4axWOgy0y3VXuiVJRMMhCV9lSijDM4

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="hari.jpeg"
Content-Type: image/jpeg

< C:\Users\Harish\Desktop\hari.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###################  UPDATE
##### Edit password
PATCH http://localhost:8080/api/jobseeker/editpassword
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg1NTc1MTI3LCJleHAiOjE1OTE1NzUxMjd9.cPBpN-8uFH1AF4axWOgy0y3VXuiVJRMMhCV9lSijDM4

{
  "password":"1234567890"
}
###   Job Accepting by Seeker
PATCH http://localhost:8080/api/jobseeker/searchjobs/byjobid/1/isaccepted
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg1NTc1MTI3LCJleHAiOjE1OTE1NzUxMjd9.cPBpN-8uFH1AF4axWOgy0y3VXuiVJRMMhCV9lSijDM4

### udpating profile
PATCH http://localhost:8080/api/jobseeker/editprofile
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTg1NTc1MTI3LCJleHAiOjE1OTE1NzUxMjd9.cPBpN-8uFH1AF4axWOgy0y3VXuiVJRMMhCV9lSijDM4

{
  "contactNumber" : 8977777777,
   "address" : "Jharkhand abcdefghtikjjh"
}
###  Logging out from Seeker Account
DELETE http://localhost:8080/api/jobseeker/logout